### PR TITLE
Update for Lispworks compatibility on MacOSX

### PR DESCRIPTION
**Pull request by dbmcclain**
self explanatory

### CODE REVIEW

**Comment by glv2** [comment]
I can't test this as I don't have any hardware running MacOSX, but is ```(:macosx "libzstd.dylib")``` really specific to Lispworks? Won't other CL implementation also need that on MacOSX?

**Comment by dbmcclain** [comment]
Hi glv2,

All I can tell you is that the symbol :MACOSX is defined when running on Mac OSX in Lispworks *FEATURES*. I do not know what symbols are defined in *FEATURES* in other Lisp environments. Perhaps it is, or perhaps it isn’t. 

I see no harm in eliding the #+:LISPWORKS8  since we know that Mac OS always needs the .dylib. But then perhaps on other Lisp versions the C FFI already knows that, and not for Lispworks?

- DM

**Comment by glv2** [comment]
Do you also have ```:DARWIN``` in ```*FEATURES*```? I saw some libraries are using that.

**Comment by dbmcclain** [comment]
Just checked, and yes - I do have :DARWIN defined in *FEATURES* on LWM/8.

**Comment by glv2** [comment]
Ok, pushed as b07c2d4fd6ccf8c8f418ffa5a6e5de7f674e9b34.
Thanks.

**Pull request closed without merging**
